class DRL_MCM_Defaults extends Object config(WOTCDisposableLaunchers_DEFAULT);

var config int VERSION_CFG;

var config bool DRL_STAT_PENALTIES_ENABLED;
var config bool DRL_STAT_PENALTIES_APPLIED_TO_HEAVY_ARMOR;
var config bool UTILITY_DRL_OCCUPIES_TWO_SLOTS;
var config bool UTILITY_DRL_MUTUALLY_EXCLUSIVE_WITH_GRENADES;

var config array<EInventorySlot> DRL_ALLOWED_INVENTORY_SLOTS;

/*
`GETMCMVAR(DRL_STAT_PENALTIES_APPLIED_TO_HEAVY_ARMOR)
`GETMCMVAR(UTILITY_DRL_OCCUPIES_TWO_SLOTS)
`GETMCMVAR(UTILITY_DRL_MUTUALLY_EXCLUSIVE_WITH_GRENADES)
*/